### ISSUE TITLE
Update to Elasticsearch 8.8.2

### ISSUE THREAD

**Issue by seljuck** [R0Wi/elasticsearch-nextcloud-docker#9]
Hello,

The Fulltextsearch:elasticsearch is now referencing Elasticsearch 8.8.2.

Can I just change the tag to 8.8.2?

If not, can you update to use that version?

Thanks

**Comment by seljuck** [comment]
Along with this update request. I noticed that the docker file has this line

ARG ELASTIC_IMAGE=elasticsearch:7.16.1

Would that need to be updated as well?

**Comment by R0Wi** [comment]
This is just the fallback value. It gets overwritten by the build https://github.com/R0Wi/elasticsearch-nextcloud-docker/blob/master/.github/workflows/build.yml#L30

I updated the image accordingly. Would be happy to get some feedback if the new version works correctly together with NC Fulltextsearch :+1:

**Comment by seljuck** [comment]
Thanks for the quick response! I'll let you know how it goes.

**Comment by seljuck** [comment]
Just did docker-compose pull and got this error message.

ERROR: for elasticsearch  manifest for r0wi/elasticsearch-nextcloud-docker:8.8.2 not found: manifest unknown: manifest unknown
ERROR: manifest for r0wi/elasticsearch-nextcloud-docker:8.8.2 not found: manifest unknown: manifest unknown

**Comment by R0Wi** [comment]
Sorry, I forgot to create the new release. Please try again

**Comment by seljuck** [comment]
I have it up and running. Thank you for your help!
The only thing I had to change was using localhost. That did not work from my Nextcloud container. 

In my Nextcloud docker-compose.yml I had to add:
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
in my elasticsearch docker-compose.yml file I had to modify the ports section
    ports:
      - 172.17.0.1:9200:9200

In the FullTextSearch settings in NextCloud the URL 
  http://elastic:password@host.docker.internal:9200

This allowed my Nextcloud container to reach the elasticsearch container.

**Comment by R0Wi** [comment]
Glad to hear that things are working now!

Regarding your network issue, I'd rather recommend to use the Docker virtual network to connect the Elastic container with the Nextcloud one instead of binding the ES container to a host port and trying to access the hosts network stack. You have basically two options to achieve this. One is to use the same `docker-compose.yml` for both the Nextcloud and Elastic container and connect via `container_name`:

```yaml
version: '2.2'
services:
  elasticsearch:
    image: r0wi/elasticsearch-nextcloud-docker:latest
    container_name: elasticsearch_nc
    networks:
      - nextcloud_infrastructure
    #...
  nextcloud:
    image: nextcloud:latest
    networks:
      - nextcloud_infrastructure
    #...
networks:
  nextcloud_infrastructure:
``` 

If you're using two different `docker-compose.yml` files, you need to define the network in one of the two files and reference it via name in the other one. For example

`docker-compose.yml` for nextcloud:

```yaml
version: '2.2'
services:
  nextcloud:
    image: nextcloud:latest
    networks:
      - nextcloud_infrastructure
    #...
networks:
  nextcloud_infrastructure:
```

for Elastic:

```yaml
version: '2.2'
services:
  elasticsearch:
    image: r0wi/elasticsearch-nextcloud-docker:latest
    container_name: elasticsearch_nc
    networks:
      - nextcloud_infrastructure
    #...
networks:
  nextcloud_infrastructure:
    external: true
```

The key here is the `external: true` which will let Docker search for the named network `nextcloud_infrastructure` globally on the system.

In both versions the NC container should be able to connect to the ES container via `http://elasticsearch_nc:9200`.

Cheers
